# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SimplePass < Formula
  desc "Simple password management via a simple cli tool
"
  homepage "https://github.com/gfcroft/simple-pass"
  version "0.1.0"
  license "Apache 2.0"

  depends_on "git"
  depends_on "npm"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gfcroft/simple-pass/releases/download/v0.1.0/simple-pass_0.1.0_darwin_arm64.tar.gz"
      sha256 "7f00e8aa346acb4ad1231e9cf643c4ec9418dc039cfce745cc4a17d92cad4884"

      def install
        bin.install "simple-pass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gfcroft/simple-pass/releases/download/v0.1.0/simple-pass_0.1.0_darwin_amd64.tar.gz"
      sha256 "dc93856cd0c07e36879f23d778d26800b3ce92c166f493316af0f3204bb42062"

      def install
        bin.install "simple-pass"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gfcroft/simple-pass/releases/download/v0.1.0/simple-pass_0.1.0_linux_arm64.tar.gz"
      sha256 "f88c422b94b70758c8e62affef108511a7c5911b532ce7c8191fa6d6e106fe63"

      def install
        bin.install "simple-pass"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gfcroft/simple-pass/releases/download/v0.1.0/simple-pass_0.1.0_linux_amd64.tar.gz"
      sha256 "2bd43d3bdc63ac9e1f74db9a9bc550fa2108a20ff7f90a5005220d7287f66bee"

      def install
        bin.install "simple-pass"
      end
    end
  end

  def caveats
    <<~EOS
      After install (or update) see

      $ simple-pass -h
    EOS
  end
end
